repository:
  # See https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#edit for all available settings.

  # A short description of the repository that will show up on GitHub
  description: Custom HTML element for inputting string data in forms

  # A URL with more information about the repository
  homepage: https://auro.alaskaair.com/components/auro/input

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: duplicate
    color: cde6ff
    description: This Issue or Pull Request already exists
  - name: good first issue
    color: 6bb7fb
    description: Good for newcomers
    aliases:
    - beginner-friendly
    - beginner
    - good-starter-issue
    - good for beginner
    - Good for beginners
    - starter-issue
    - starter
  - name: help wanted
    color: 2492eb
    description: Extra attention is needed, this user requires assistance to complete
      the work
  - name: 'Epic: Project Version Zero'
    color: '222222'
    description: Identifier of project epic issue.
  - name: 'Project: Version Zero'
    color: '222222'
    description: Issues related to the epic Project Zero
  - name: 'Epic: Auro User Definition'
    color: '222222'
    description: Identifier of project epic issue.
  - name: 'Project: Auro User Definition'
    color: '222222'
    description: Issues related to the epic User Research
  - name: 'Epic: Doc Site Strategy'
    color: '222222'
    description: Identifier of project epic issue.
  - name: 'Project: Doc Site Strategy'
    color: '222222'
    description: Issues related to the epic Doc Site Strategy
  - name: 'Status: Epic in progress'
    color: '222222'
    description: Epic has issue(s) in progress
  - name: 'Priority: Critical'
    color: b82b47
    description: Issues that need immediate attention
  - name: 'Priority: High'
    color: f65b7b
    description: Issues that need attention soon
  - name: 'Priority: Low'
    color: ff94a7
    description: Issues that need not be forgotten
  - name: 'Priority: Audit'
    color: ff94a7
    description: Priority status specifically for DS Audit use
  - name: released
    color: A9A9A9
    description: Completed work has been released
  - name: 'Status: Backlogged'
    color: e2ffcd
    description: Backlogged item is a proposed question or solution, the user is requesting
      feedback
    aliases:
    - idea
    - Idea
    - proposal
    - Proposal
    - discussion
  - name: 'Status: Prioritized for work'
    color: d0fba6
    description: Proposal has been prioritized for development (issues only)
  - name: 'Status: Work In Progress'
    description: Issue or Pull Request work is in Progress
    color: c0e585
  - name: 'Status: Review Needed'
    color: 91be62
    description: Work is completed, user is requesting feedback
  - name: 'Status: Complete and Ready to Merge'
    color: 5e8741
    description: Owner has completed work and considers it ready to be merged
  - name: 'Status: Blocked'
    color: df0b37
    description: Progress on the issue is Blocked, immediate attention is required
    aliases:
    - blocked
  - name: 'Status: Discovery'
    color: c1daf0
    description: New work that is still in a discovery phase
  - name: 'Status: PR Welcome'
    color: 569ed7
    description: Assigned to issues, requesting general public support
    aliases:
    - Patch Welcome
    - 'Status: Ready for PR'
  - name: 'Status: Abandoned'
    color: 156fad
    description: The issue or Pull Request is wontfix
    aliases:
    - wontfix
    - invalid
  - name: 'Type: Bug'
    color: df0b37
    description: Bug or Bug fixes
    aliases:
    - bug
  - name: 'Type: Breaking Change'
    color: b88624
    description: Includes breaking changes, will require MAJOR version release
    aliases:
    - breaking
    - breaking-change
  - name: 'Type: Feature'
    color: e5ad07
    description: New Feature
    aliases:
    - enhancement
  - name: 'Type: Design'
    color: e5ad07
    description: New Design
    aliases:
    - enhancement
  - name: 'Type: Content/data'
    color: ffd200
    description: Adding or editing new content or data to the repo
    aliases:
    - enhancement
  - name: 'Type: Refactoring'
    color: ffdb67
    description: A code change that neither fixes a bug nor adds a feature
    aliases:
    - refactor
  - name: 'Type: Testing'
    color: fff0cd
    description: Adding missing tests or correcting existing tests
    aliases:
    - test
    - testing
  - name: 'Type: Documentation'
    color: f26135
    description: Documentation only changes
    aliases:
    - documents
    - document
  - name: 'Type: Maintenance'
    color: b83302
    description: Repository Maintenance
    aliases:
    - greenkeeper
    - maintenance
  - name: 'Type: CI'
    color: b83302
    description: Changes to CI configuration files and scripts
    aliases:
    - travis
    - ci
    - circleci
  - name: 'Type: Question'
    color: b83302
    description: Further information is requested
    aliases:
    - question
  - name: 'Type: Dependencies'
    color: b83302
    description: Pull requests that update a dependency file
    aliases:
    - dependencies
  - name: 'Type: High Risk'
    color: b83302
    description: Work is high risk, pay close attention to updates and tests
